### PR TITLE
Initial version of beautifying code editors

### PR DESCRIPTION
**Pull request by JonathanWolfe**
- [x] Ready to merge

Here's the initial version of the code beautifier. Beautifies HTML, CSS, & JS - but none of their preprocessor cousins. ( From issue #341 )

It functions, but lacks two important features:
1. **Hot-keys** - I'm probably just being stupid as to why it doesn't work
2. **Beautify settings** - Wasn't sure how you wanted to store them with the rest of the settings and how to display that to people

Should probably also minify the beautifier files.

I tried to copy tern's implementation as much as possible and keep code style conventions.

I'm gonna keep working on (1) but I think (2) might be an implementation detail you guys will want to handle.

### CODE REVIEW

**Comment by ramtob** [comment]
Hello. Is the beautify feature implemented? If so, how can I use it? Thanks

**Comment by remy** [comment]
@ramtob open the keyboard shortcuts (from the help) and blamo: https://cloudup.com/cqm35U4Z_dk

**Comment by ramtob** [comment]
@remy I tried the keyboard shortcut (Ctrl-Shift-L according to http://jsbin.com/help/keyboard-shortcuts), several times. It did work once, but most of the times it didn't work. Instead, it prints "context reset" on the console panel, and moves the focus to that panel. See https://cloudup.com/cXjQbcokJIK

**Comment by ramtob** [comment]
Anyone?

**Pull request merged**
