### PR TITLE
Add jQuery 3.1 & jQuery UI 1.12.0, update jQuery to be used with UI 1.11.4

### PR DESCRIPTION
**Pull request by mgol**

### CODE REVIEW

**Comment by mgol** [comment]
Just in case you felt comfortable with that - if you added me as a contributor to this repo, I, as a member of the jQuery team, could keep the jQuery-related packages up to date in this file. I promise I won't touch anything else without a proper PR.

**Comment by remy** [comment]
@mgol I've been meaning to post a reach-out blog post on jsbin to get some people with commit rights so they can do this stuff too.

I'll get you in and write up the release process (which is simple enough as a large part is automated).

**Comment by remy** [comment]
…and of course contains nearly zip all tests…

**Comment by mgol** [comment]
Thanks! I'm waiting for the details then.

**Pull request merged**
