### PR TITLE
Add reactjs custom subdomain

### PR DESCRIPTION
**Pull request by spicyj**

### CODE REVIEW

**Comment by spicyj** [comment]
Hey @remy – not sure if this only comes with some business arrangement or if it's open to anyone (I don't think I ever heard back from you the last time I tried to find out) but I thought I'd send this in and see what the word is. Thanks!

**Comment by remy** [comment]
Well, I did get in touch with FB, but there was no response. Basically these kinds of services were supposed to help sustain jsbin (when infact it just drives more users to jsbin to use the service for free - which is great for my ego, but pretty terrible for resources - it's kind of the opposite of growth hacking that I need to do!).

Anyway, is there any reason why it should be reactjs.jsbin.com instead of react.jsbin.com?

**Comment by spicyj** [comment]
No real reason (consistency with emberjs?), I was torn and I think I do like react.jsbin.com better – changed.

Sorry about the bad communication – I emailed you twice in Feb 2014 and didn't hear back but I talked to some folks around here and see that you did manage to get in touch. I don't think this is worth enough for us when there are other free options with similar functionality (including unbranded JS Bin), but I figure that React users are no less likely to sign up for JS Bin pro accounts than your average user so this could prove beneficial for you. Feel free to close if you don't want to take this.

**Comment by remy** [comment]
Fuck it. This is supposed to be a paid part of JS Bin, but I can't get through the walls of bureaucracy, but ¯\_(ツ)_/¯

**Pull request merged**
