### PR TITLE
removing extra columns from mysql full db creation sql

### PR DESCRIPTION
**Pull request by loudwinston**
Remove extra columns from mysql database creation script.  I assume these are for an in-progress feature(s) that hasn't been merged to master yet, but having them included in the master db creation script causes an error when saving a bin due to missing values for NOT NULL columns.

### CODE REVIEW

**Comment by mfilotto** [comment]
Hi guys,
I'm facing the same issue today with jsbin 3.27.3 and mysql 5.6.22.
@loudwinston  How did you solve the problem please ?

**Comment by koraysels** [comment]
can anybody post the solution to this problem ? I cannot seem to wrap my head around it..  should we modify the code in models/bin.js  ??

**Comment by koraysels** [comment]
Okay if I add default values to  "streaming_read_key/active_tab and  active_cursor -1 ?"

```
CREATE TABLE `sandbox` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `javascript` mediumtext COLLATE utf8mb4_unicode_ci,
  `html` mediumtext COLLATE utf8mb4_unicode_ci,
  `created` datetime DEFAULT NULL,
  `last_viewed` datetime DEFAULT NULL,
  `url` char(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active` char(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'y',
  `reported` datetime DEFAULT NULL,
  `streaming` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'n',
  `streaming_key` char(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streaming_read_key` char(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `active_tab` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `active_cursor` int(11) NOT NULL DEFAULT '-1',
  `revision` int(11) DEFAULT '1',
  `css` mediumtext COLLATE utf8mb4_unicode_ci,
  `settings` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `viewed` (`last_viewed`),
  KEY `url` (`url`(191)),
  KEY `streaming_key` (`streaming_key`),
  KEY `spam` (`created`,`last_viewed`),
  KEY `revision` (`url`(191),`revision`)
) ENGINE=InnoDB AUTO_INCREMENT=9002830 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Comment by koraysels** [comment]
now i still need to work out why the code in the ui is not working .. 

I get a lot of ERR_SSL_PROTOCOL_ERROR in chrome console... very strange

image

**Comment by koraysels** [comment]
Okay as a temporary fix I chenged the following line 
https://github.com/jsbin/jsbin/blob/108e15e15350a294cee957cd9f928372a1fe79ce/views/runner.html#L33

to ` {{#scripts}}<script src="{{static}}{{.}}"></script>`

**Pull request closed without merging**
