### PR TITLE
Correct NODE_ENV -> JSBIN_ENV in self hosting doc.

### PR DESCRIPTION
**Pull request by leeyeh**

### CODE REVIEW

**Comment by remy** [comment]
Curious. Does `NODE_ENV` not work? It's what I'm using in production myself...

**Comment by leeyeh** [comment]
I see no reason `NODE_ENV` should work: https://github.com/jsbin/jsbin/blob/f8af9bedbaed4e52ebc0fa77661a0ab9da172d5d/lib/config.js#L95

Here are my deploy logs: https://gist.github.com/leeyeh/3d0534ca6f270bd5b718#file-gistfile1-txt-L1

**Comment by remy** [comment]
That's nice, but here's the script that runs jsbin in production, in production mode: https://github.com/jsbin/production/blob/master/apps.jsbin.com/etc/init/jsbin.conf#L18

**Comment by leeyeh** [comment]
Maybe [this config](https://github.com/jsbin/production/blob/master/apps.jsbin.com/WWW/jsbin/config.local.json) is a actually taking effort?

**Pull request closed without merging**
