### PR TITLE
Make setting es6/babel as a preprocessor work when pre-populating bins with POST request

### PR DESCRIPTION
**Pull request by kirjs**
For some reason didn't work before

### CODE REVIEW

**Comment by soookie** [comment]
Hmmmmm you should know I know this stuff good yo

**Comment by remy** [comment]
I'm not sure this is right, but I need to dig more into what's actually wrong. What do you see without this fix?

**Comment by kirjs** [comment]
So if you POST to jsbin.com:
```json
{
  "html": "hi",
  "css": "",
  "es6": "let x = 1;"
}
```

The result would be empty JS tab. 
screen shot 2016-01-08 at 1 22 34 pm

After the fix the result would be pre-populated ES6/Babel tab.

**Comment by remy** [comment]
I'm worried there's two changes in there tho. The router one looks OK, but I'm not sure about the processor/index one. Can you repeat your test with that change reverted?

**Comment by kirjs** [comment]
Processor
`processor/index` is actually the one which actually makes it work (It also makes es6/babel consistent with `coffeescript` and `ts` and others).

The router one as far as I remember just adds babel as as a synonym to ES6, e.g.
```json
{
  "html": "hi",
  "css": "",
  "babel": "let x = 1;"
}```

**Comment by jesstelford** [comment]
LGTM :+1:

I'd love to see this live on jsbin!

**Comment by kirjs** [comment]
Just wanted to follow up on this one: any chance we can get it in? Thanks!

**Comment by remy** [comment]
Needs a PR to get in.

**Comment by kirjs** [comment]
What kind of PR is needed?

**Comment by remy** [comment]
lol - didn't know what I was talking about!

Sod it, merging. I'll deal with the fallout if there is any...

**Comment by kirjs** [comment]
Awesome, thanks!

**Pull request merged**
