### PR TITLE
Update the name of the config file to the name that is actually being…

### PR DESCRIPTION
**Pull request by riznob**
… used. Add a Running section.

### CODE REVIEW

**Comment by remy** [comment]
Was this for this repo?

**Comment by riznob** [comment]
Yes.

**Comment by remy** [comment]
Then do you want to explain the commits, since they don't currently make any sense to be merged (`config.local.json` is the default config jsbin looks for).

**Comment by riznob** [comment]
Please see line 11 and line 20 of Gruntfile.js. The default is indeed config.node.json.

**Comment by remy** [comment]
Oh god, yeah, that gruntfile isn't used at all except for building the production (min) js files.

The PR should be killing off a tonne of unused gruntfile junk! Sorry you've been going down the wrong path.

**Pull request closed without merging**
