### PR TITLE
Update Ember library to v1.11.1 and Ember data to v1.0.0-beta.16.1

### PR DESCRIPTION
**Pull request by HeroicEric**
- Updates the Ember.js library to v1.11.1, which is the current stable version.
- Updates the Ember data library to v1.0.0-beta.16.1.

[Ember Release Builds](http://emberjs.com/builds/#/release)

### CODE REVIEW

**Comment by remy** [comment]
Doh, sorry, I merged in a new change that caused a conflict on this. Any chance you can submit an updated PR?

**Comment by HeroicEric** [comment]
The merge conflicts are fixed

**Comment by rwjblue** [comment]
@HeroicEric - Mind updating to 1.11.0?

**Comment by HeroicEric** [comment]
@rwjblue Sure. Does that mean there is a release coming? :smile:

**Comment by rwjblue** [comment]
@HeroicEric - Yep, as of about 10 minutes ago :wink: 

http://emberjs.com/blog/2015/03/27/ember-1-11-0-released.html

**Comment by rwjblue** [comment]
Thanks for updating!

**Comment by HeroicEric** [comment]
Updated to the latest versions for both ember and ember-data

**Pull request merged**
