### PR TITLE
Updated package.json to work on a fresh install

### PR DESCRIPTION
**Pull request by James9074**
A few updates to help jsbin work out of the box with node 7+ and npm 4+. The build still passes with your node/npm version (0.10.40/1.4.28) as well.

- memcached has been throwing errors with hashring on every install I've ever done of jsbin, I always have to manually update this and sqlite to get the build to work.
- sqlite follows the same issue as memcached, with node-gyp build failures across several target machines, updated to get rid of that.
- connect is required, but doesn't install under express when using ```npm install```

For reference, these fixes were found in a closed jsbin issue: https://github.com/jsbin/jsbin/issues/2958

### CODE REVIEW

**Comment by remy** [comment]
I can't merge this, partly because it requires mysql in production and some tight requirements on memcache (unrelated to mysql), but also because you've just set the default flag on pro to true for all new entries. I assume this is for your own branch (and am closing for now)?

**Comment by James9074** [comment]
Hah - I totally forgot that I submitted this PR last month, glad you caught that - that sure looks malicious doesn't it? So sorry @remy!

I do have a question though, what OS are you using for dev here? On Ubuntu 16.04 (and related friends) memcached fails pretty hard every single time due to hashring (node-gyp fails). Some thing with sqlite 2. I've never been able to just pull and install jsbin across various node/npm versions on Ubuntu 16.04 x64

Might be worth putting connect in packages as well though, since it doesn't auto install as a dependency for some reason. I can submit a PR for just that if you agree.

**Comment by remy** [comment]
For dev, I'm on a mac, but in production, it's Ubuntu 14.

I do have a private branch that upgrades the entire code base of jsbin to move from node@0.10 to node@6 and it would also likely drop memcache entirely…maybe!

**Comment by James9074** [comment]
Interesting, I'll set the base image to 14 then and give it a go. Have you thought about using containers? I set JSBin up in docker for both dev and prod in our environment (since we try to run everything through Rancher), didn't take much effort at all. If you're ever interested in that I'd be happy to share the dockerfile + compose config. Might help people get up and running faster using identical environments.

**Pull request closed without merging**
