### PR TITLE
replace/update 6to5 with Babel

### PR DESCRIPTION
**Pull request by maxhoffmann**
[6to5](http://babeljs.io/blog/2015/02/15/not-born-to-die/) was renamed to [Babel](http://babeljs.io/) and has rapidly become the most popular ES6 transpiler [supporting most of its features](http://kangax.github.io/compat-table/es6/). Additionally it supports JSX and facebook itself is [switching to Babel](https://github.com/facebook/esprima/issues/111) for that. Removing the JSX transpiler is not included in this pull request though.

Changes:
- [x] removed 6to5 as a preprocessor
- [x] removed 6to5 captureStackTrace monkey patch
- [x] added babel as a preprocessor
- [x] compiling with `stage: 0` option that enables playing around with ES7 features

Not included is babel’s `browser-polyfill.js`, as I was not sure how to include multiple files. I tried using `getScript`, but that didn’t work. Even without them this pull request can be merged.

### CODE REVIEW

**Comment by remy** [comment]
This is excellent - thank you!

Regarding the `browser-polyfill.js` - did you try the technique [here](https://github.com/maxhoffmann/jsbin/blob/master/public/js/processors/processor.js#L462). Typically the `browser-polyfill.js` would be put in the `/public/js/vendor/` directory, and should load from there.

Also, it's a little more work, but [pennyworth](https://github.com/jsbin/pennyworth) also needs to be updated - though I suspect it's a simple enough change.

However! (sorry, I'm writing this as I work it out), the `6to5` target (in pennyworth) needs to be left in place - i.e. babel needs to be added and not replace anything that's there (though the `to5/index.js` could just require in the new `babel` target in the same way the [SCSS](https://github.com/jsbin/pennyworth/blob/master/targets/scss/index.js) does from Sass).

That might sound confusing...

Let me know how you get on!

**Comment by maxhoffmann** [comment]
Yes, I tried [this](https://github.com/maxhoffmann/jsbin/blob/master/public/js/processors/processor.js#L462) technique. I just figured out that the polyfills are loading, but added to the wrong context. They are patching `window` of jsbin.com not inside the iframe. Is there any way I can force the execution of the polyfills to be inside of the runner’s context?

Regarding pennyworth, I’ll take look at it tomorrow. The notes about 6to5 not being replaced are only related to pennyworth, aren’t they? Or should I undo removing 6to5 from this pull request as well?

**Comment by maxhoffmann** [comment]
By the way, when I tried setting up jsbin locally it failed at `npm install` because of an outdated version of sqlite3 that is incompatible with node `0.12`. It took some time for me to figure out why it wasn’t compiling. Adding a note to the readme would help a lot. :)

**Comment by maxhoffmann** [comment]
Any update on this? I’d really like to use Babel on jsbin. :)

**Comment by maxhoffmann** [comment]
Thanks a lot! :+1:

One thing that’s still open is loading `browser-polyfill.js` inside the output iframe:

> I just figured out that the polyfills are loading, but added to the wrong context. They are patching window of jsbin.com not inside the iframe. Is there any way I can force the execution of the polyfills to be inside of the runner’s context?

**Pull request merged**
