### PR TITLE
Generate QR code for link sharing

### PR DESCRIPTION
**Pull request by mingzeke**

### CODE REVIEW

**Comment by remy** [comment]
This is all I see in the share menu - https://cloudup.com/cF1Cy24_fsC - but also, I'm not convinced that anyone actually needs a qrcode.

Particularly as all the bins have shortcut urls - like jsbin.com/rem/last

**Comment by mingzeke** [comment]
This is what I saw - https://cloudup.com/cmgfUJzVRjT
I've tested it on Chrome, Safari and Firefox.
It should look fine.

During our project development, we use jsbin to write, run and preview on various devices and screens.
With qrcode, we found testing on mobile devices is easier - no more typing, just snap it.

**Comment by remy** [comment]
Yeah...that qrcode didn't work on my test, but also hasn't been designed
into the share panel very well - its just been slapped in. Maybe a single
link to a generated qrcode (using googles charting api, thus no need for
the extra script) and then it might work inside the design of the share
panel.

**Comment by mingzeke** [comment]
Yeah...I agreed that qrcode block is not so fitted into the design of the share panel.
I'll re-design it and make some improvements.
Thanks for the advice!

**Pull request closed without merging**
